name: Build examples/bzlmod

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            os: ubuntu-latest
          - name: linux-arm64
            os: ubuntu-22.04-arm64
          - name: macos-arm64
            os: macos-14
          - name: macos-intel
            os: macos-13
          - name: windows-amd64
            os: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build example target
        run: bazel build //:main
        working-directory: examples/bzlmod
        shell: bash
