name: Build examples/bzlmod

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: local-linux-x86_64
            os: ubuntu-24.04
            command: bazel build //:main --noremote_accept_cached --noremote_upload_local_results
          - name: local-macos-arm64
            os: macos-15
            command: bazel build //:main --noremote_accept_cached --noremote_upload_local_results
          - name: local-macos-x86_64
            os: macos-15-intel
            command: bazel build //:main --noremote_accept_cached --noremote_upload_local_results
          - name: local-windows-x86_64
            os: windows-2022
            command: bazel build //:main
          - name: local-linux-x86_64-rbe-linux-x86_64
            os: ubuntu-24.04
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
          - name: local-linux-x86_64-rbe-linux-arm64
            os: ubuntu-24.04
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_arm64
          - name: local-windows-x86_64-rbe-linux-x86_64
            os: windows-2022
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --platforms=@toolchains_buildbuddy//platforms:linux_x86_64 \
                --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_x86_64 \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64 \
                --remote_local_fallback=false \
                --strategy=CppCompile=remote \
                --incompatible_enable_cc_toolchain_resolution \
                --host_platform=@toolchains_buildbuddy//platforms:linux_x86_64 \
                --toolchain_resolution_debug=cpp \
                --toolchain_resolution_override=@bazel_tools//tools/cpp:toolchain_type=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
          - name: local-windows-x86_64-rbe-linux-arm64
            os: windows-2022
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_arm64 \
                --remote_local_fallback=false \
                --strategy=CppCompile=remote \
                --incompatible_enable_cc_toolchain_resolution \
                --host_platform=@toolchains_buildbuddy//platforms:linux_x86_64 \
                --toolchain_resolution_debug=cpp \
                --toolchain_resolution_override=@bazel_tools//tools/cpp:toolchain_type=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
          - name: local-macos-x86_64-rbe-linux-x86_64
            os: macos-15-intel
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
          - name: local-macos-x86_64-rbe-linux-arm64
            os: macos-15-intel
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_arm64
          - name: local-macos-arm64-rbe-linux-x86_64
            os: macos-15
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
          - name: local-macos-arm64-rbe-linux-arm64
            os: macos-15
            command: >-
              bazel build //:main \
                --noremote_accept_cached \
                --noremote_upload_local_results \
                --config=remote-linux \
                --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" \
                --experimental_platform_in_output_dir \
                --platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_arm64 \
                --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build example target
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: ${{ matrix.command }}
        working-directory: examples/bzlmod
        shell: bash
