name: Build bzlmod example

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            os: ubuntu-latest
            shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Build example target
        run: bazel build //:main
        working-directory: examples/bzlmod
        shell: ${{ matrix.shell }}
