name: Publish to BCR
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: git tag to publish
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.3
    with:
      tag_name: ${{ inputs.tag_name }}
      # GitHub repository which is a fork of the upstream where the Pull Request will be opened.
      registry_fork: buildbuddy-io/bazel-central-registry
      draft: false
      # We will open pull requests against the upstream BCR manually.
      open_pull_request: false
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      # Necessary to push to the BCR fork
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
