# Tag a new release using https://github.com/marketplace/actions/conventional-commits-versioner-action
#
# This is easier than having to run manual `git` operations on a local clone.

name: Tag a Release
on:
  # Allow devs to tag manually through the GitHub UI.
  # For example after landing a fix that customers are waiting for.
  workflow_dispatch:
jobs:
  tag:
    permissions:
      contents: write # allow create tag
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.ccv.outputs.new-tag }}
      new-tag-version: ${{ steps.ccv.outputs.new-tag-version }}
      new-tag-version-type: ${{ steps.ccv.outputs.new-tag-version-type }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Need enough history to find the prior release tag
          fetch-depth: 0
      - name: Bump tag if necessary
        id: ccv
        uses: smlx/ccv@v0.10.0
  release:
    needs: tag
    uses: ./.github/workflows/release.yaml
    with:
      tag_name: ${{ needs.tag.outputs.new-tag-version }}
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
    if: needs.tag.outputs.new-tag == 'true' && needs.tag.outputs.new-tag-version-type != 'major'
    permissions:
      contents: write
      id-token: write
      attestations: write
