# Create a new tag manually
name: Tag a Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: git tag to create (e.g., v1.0.0)
        required: true
        type: string
jobs:
  tag:
    permissions:
      contents: write # allow create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and push tag
        run: |
          git tag ${{ inputs.tag_name }}
          git push origin ${{ inputs.tag_name }}
